<?php

namespace ContainerHgYkt9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0fYq9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V0f_yq9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V0f_yq9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventCategoryRepository' => ['privates', 'App\\Repository\\EventCategoryRepository', 'getEventCategoryRepositoryService', true],
        ], [
            'eventCategoryRepository' => 'App\\Repository\\EventCategoryRepository',
        ]);
    }
}
