<?php

namespace ContainerHgYkt9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ABOx9AFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ABOx9AF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ABOx9AF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.ABOx9AF.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.ABOx9AF": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'eventRepository' => 'App\\Repository\\EventRepository',
        ]);
    }
}
