<?php

namespace ContainerHgYkt9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R0gRNt6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R0gRNt6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R0gRNt6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]);
    }
}
