<?php

namespace ContainerHgYkt9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCategoryTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EventCategoryType' shared autowired service.
     *
     * @return \App\Form\EventCategoryType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EventCategoryType'] = new \App\Form\EventCategoryType();
    }
}
