<?php

namespace ContainerHgYkt9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonthlyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MonthlyController' shared autowired service.
     *
     * @return \App\Controller\MonthlyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MonthlyController'] = $instance = new \App\Controller\MonthlyController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\MonthlyController', $container));

        return $instance;
    }
}
