<?php

namespace ContainerHgYkt9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWarehouseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WarehouseController' shared autowired service.
     *
     * @return \App\Controller\WarehouseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\WarehouseController'] = $instance = new \App\Controller\WarehouseController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\WarehouseController', $container));

        return $instance;
    }
}
