<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EyPMOHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eyPM_OH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eyPM_OH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'task' => ['privates', '.errored..service_locator.eyPM_OH.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.eyPM_OH": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'task' => 'App\\Entity\\Task',
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]);
    }
}
