<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHtkTSXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zHtkTSX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zHtkTSX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventCategory' => ['privates', '.errored..service_locator.zHtkTSX.App\\Entity\\EventCategory', NULL, 'Cannot autowire service ".service_locator.zHtkTSX": it needs an instance of "App\\Entity\\EventCategory" but this type has been excluded in "config/services.yaml".'],
            'eventCategoryRepository' => ['privates', 'App\\Repository\\EventCategoryRepository', 'getEventCategoryRepositoryService', true],
        ], [
            'eventCategory' => 'App\\Entity\\EventCategory',
            'eventCategoryRepository' => 'App\\Repository\\EventCategoryRepository',
        ]);
    }
}
