<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RJYuwJfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rJYuwJf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rJYuwJf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'company' => ['privates', '.errored..service_locator.rJYuwJf.App\\Entity\\Company', NULL, 'Cannot autowire service ".service_locator.rJYuwJf": it needs an instance of "App\\Entity\\Company" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'company' => 'App\\Entity\\Company',
            'entityManager' => '?',
            'userPasswordHasher' => '?',
        ]);
    }
}
