<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_BdKR0TNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.BdKR0TN' shared service.
     *
     * @return \App\Controller\EventCategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\EventController::newAlmacen()": the $eventCategoryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EventCategoryRepository". Did you forget to add a use statement?');
    }
}
