<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompany2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LMAnW02.App\Entity\Company' shared service.
     *
     * @return \App\Entity\Company
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LMAnW02": it needs an instance of "App\\Entity\\Company" but this type has been excluded in "config/services.yaml".');
    }
}
