<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CompanyType' shared autowired service.
     *
     * @return \App\Form\CompanyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CompanyType'] = new \App\Form\CompanyType();
    }
}
