<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GN0t2am.App\Entity\EventCategory' shared service.
     *
     * @return \App\Entity\EventCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GN0t2am": it needs an instance of "App\\Entity\\EventCategory" but this type has been excluded in "config/services.yaml".');
    }
}
