<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCategoryRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\EventCategoryRepository' shared autowired service.
     *
     * @return \App\Repository\EventCategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EventCategoryRepository'] = new \App\Repository\EventCategoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
