<?php

namespace ContainerUfJqh6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\JobController' shared autowired service.
     *
     * @return \App\Controller\JobController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\JobController'] = $instance = new \App\Controller\JobController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\JobController', $container));

        return $instance;
    }
}
