<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfJqh6C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfJqh6C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUfJqh6C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUfJqh6C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUfJqh6C\App_KernelDevDebugContainer([
    'container.build_hash' => 'UfJqh6C',
    'container.build_id' => 'a9bc76e1',
    'container.build_time' => 1676562516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfJqh6C');
